version: "3.9"

services:
  app:
    build: .
    container_name: fastapi_app
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:15
    container_name: postgres_db
    env_file: .env
    ports:
      - "5437:5437"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
